version: '3.8'

services:
  quantum-search:
    build: .
    container_name: quantum-hyper-search
    environment:
      - PYTHONPATH=/app
      - DWAVE_API_TOKEN=${DWAVE_API_TOKEN:-}
    volumes:
      - ./examples:/app/examples:ro
      - ./data:/app/data
      - quantum_cache:/app/.quantum_cache
    ports:
      - "8080:8080"  # For potential web interface
    healthcheck:
      test: ["CMD", "python", "-m", "quantum_hyper_search.monitoring.health_check", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Redis for distributed caching
  redis:
    image: redis:7-alpine
    container_name: quantum-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Optional: Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: quantum-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

volumes:
  quantum_cache:
  redis_data:
  prometheus_data: