# Default values for quantum-hyper-search
replicaCount: 3

image:
  repository: quantum-hyper-search
  pullPolicy: Always
  tag: "1.0.0"

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: quantum-optimizer.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

monitoring:
  enabled: true
  prometheus: true
  grafana: true

security:
  enabled: true
  networkPolicies: true
