# Kubernetes Deployment for Quantum Hyper Search
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-hyper-search
  namespace: production
  labels:
    app: quantum-hyper-search
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quantum-hyper-search
  template:
    metadata:
      labels:
        app: quantum-hyper-search
    spec:
      containers:
      - name: quantum-optimization
        image: quantum-hyper-search:production
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: QUANTUM_BACKEND
          value: "dwave"
        - name: MONITORING_ENABLED
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: quantum-hyper-search-service
  namespace: production
spec:
  selector:
    app: quantum-hyper-search
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quantum-hyper-search-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quantum-hyper-search
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-config
  namespace: production
data:
  app.yml: |
    quantum:
      backends:
        - dwave
        - simulated
      optimization:
        max_iterations: 1000
        timeout: 300
      monitoring:
        prometheus_enabled: true
        metrics_port: 9090
